site_name: SolidLab Documentation Center
theme:
  name: material
  icon:
    logo: fontawesome/solid/s
  features:
    - navigation.tabs
    - announce.dismiss
  custom_dir: overrides
plugins:
  - search
nav:
  - Welcome: index.md
  - getting-started.md
  - tutorials.md
  - tools-libraries.md
  - Challenge reports: challenge-reports/index.md
  - terminology.md
  - faq.md
  - Provide feedback: https://github.com/SolidLabResearch/documentation-center/issues
copyright: Copyright &copy; 2023 <a href="https://solidlab.be/">SolidLab Flanders</a>
